In [1]:
data = {
   'beine': [4, 4, 4],
   'groesse': [35.4, 28.6, 32.7],
   'breite': [21.9, 18.7, 16.4],
   'farbe': ["Braun", "Schwarz", "Beige"],
   'label': ["Hund", "nicht Hund", "Hund"]
}

In [2]:
beine = [4, 4, 4, 4, 4]
groesse = [35.4, 28.6, 32.7, 23.9, 45.6]
breite = [21.9, 18.7, 16.4, 15.8, 25.6]
farbe = ["Braun", "Weiß", "Schwarz", "Beige", "Braun"]
label = ["Hund", "nicht Hund", "Hund", "nicht Hund", "Hund"]

In [3]:
farbe = [1, "Weiß", "Schwarz", "Beige", 1]
farbe = [1, 2, "Schwarz", "Beige", 1]
farbe = [1, 2, 3, "Beige", 1]
farbe = [1, 2, 3, 4, 1]
label = [1, "nicht Hund", 1, "nicht Hund", 1]

In [4]:
beine = [4, 4, 4, 4, 4]
groesse = [35.4, 28.6, 32.7, 23.9, 45.6]
breite = [21.9, 18.7, 16.4, 15.8, 25.6]
label = [1, 0, 1, 0, 1]

In [5]:
data = {
   'beine': [4, 4, 4, 4, 4],
   'groesse': [35.4, 28.6, 32.7, 23.9, 45.6],
   'breite': [21.9, 18.7, 16.4, 15.8, 25.6],
   'label': [1, 0, 1, 0, 1]
}

In [6]:
import numpy as np

In [7]:
beine = np.array([4, 4, 4, 4, 4])
groesse = np.array([35.4, 28.6, 32.7, 23.9, 45.6])
breite = np.array([21.9, 18.7, 16.4, 15.8, 25.6])
label = np.array([1, 0, 1, 0, 1])

In [8]:
# Mit der eckigen Klammer (als Liste) sieht es so aus:
print(np.array([35.4, 28.6, 32.7, 23.9, 45.6]))

# Und als Tupel genau gleich:
print(np.array((35.4, 28.6, 32.7, 23.9, 45.6)))

[35.4 28.6 32.7 23.9 45.6]
[35.4 28.6 32.7 23.9 45.6]


In [9]:
beine = np.array(data['beine'])
groesse = np.array(data['groesse'])
breite = np.array(data['breite'])
label = np.array(data['label'])
label.shape

KeyError: 'grosse'

In [9]:
print(breite)

[21.9 18.7 16.4 15.8 25.6]


In [10]:
data_np = np.array(data)

In [11]:
feature = np.array([data['beine'], data['groesse'], data['breite']])
print(feature)
print(feature.shape)

[[ 4.   4.   4.   4.   4. ]
 [35.4 28.6 32.7 23.9 45.6]
 [21.9 18.7 16.4 15.8 25.6]]
(3, 5)


In [12]:
# Zeilen und Spalten tauschen
print(feature.T)

[[ 4.  35.4 21.9]
 [ 4.  28.6 18.7]
 [ 4.  32.7 16.4]
 [ 4.  23.9 15.8]
 [ 4.  45.6 25.6]]
